robot_radius: 0.225

obstacle_2d_layer:
 enabled: true
 max_obstacle_height: 0.6
 min_obstacle_height: 0.0
 obstacle_range: 2.5
 raytrace_range: 5.0
 inflation_radius: 0.05
 combination_method: 1
 observation_sources: laser_scan_sensor #laser_scan_sensor2 #camera_depth
 track_unknown_space: true
 laser_scan_sensor: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
 #laser_scan_sensor2: {data_type: LaserScan, topic: /camera/scan, marking: true, clearing: true, expected_update_rate: 0}
 #camera_depth: {data_type: PointCloud2, topic:  /camera/depth/points, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 1.4}

 track_unknown_space: true

obstacle_3d_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 1
  unknown_threshold:    15
  mark_threshold:       0
  publish_voxel_map: false

  max_obstacle_height: 3.0
  min_obstacle_height: 0.0
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.05
  observation_sources: pointcloud
  pointcloud: {data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true, min_obstacle_height: 0.015, max_obstacle_height: 0.5}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"

sonar_layer:
  enabled: true
  clear_threshold: 0.2
  mark_threshold: 0.8
  topics: ["/sim_ir_left1", "/sim_ir_left2", "/sim_ir_right1", "/sim_ir_right2"]
  #topics: ["/sim_ir_left1"]
  #topics: ["/sonar0", "/sonar1", "/sonar2", "/sonar3"]
  clear_on_max_reading: true
