local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 1.5
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_2d_layer,   type: "costmap_2d::ObstacleLayer"}
   - {name: obstacle_3d_layer,   type: "costmap_2d::VoxelLayer"}
   - {name: sonar_layer,         type: "range_sensor_layer::RangeSensorLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

   
